# Generated by Django 5.1.5 on 2025-03-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactphone',
            name='type',
            field=models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcontactphone',
            name='type',
            field=models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='phone', max_length=20),
        ),
    ]
