# Generated by Django 6.0.6 on 2026-06-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapl', '0007_newsarticle_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhomeherosection',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Small label shown above the title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalhomeherosection',
            name='cta_primary_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalhomeherosection',
            name='cta_primary_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalhomeherosection',
            name='cta_primary_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalhomeherosection',
            name='cta_secondary_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalhomeherosection',
            name='cta_secondary_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalhomeherosection',
            name='cta_secondary_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalhomeherosection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalhomeherosection',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homeherosection',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Small label shown above the title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homeherosection',
            name='cta_primary_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homeherosection',
            name='cta_primary_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeherosection',
            name='cta_primary_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homeherosection',
            name='cta_secondary_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homeherosection',
            name='cta_secondary_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeherosection',
            name='cta_secondary_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homeherosection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homeherosection',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
