# Generated by Django 6.0.6 on 2026-06-18 10:44

import common.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapl', '0008_historicalhomeherosection_badge_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='footer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='site_favicon',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='site_logo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='site_name',
            field=models.CharField(default='Humana Apparels Ltd', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='site_tagline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_favicon',
            field=common.fields.OptimizedImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=common.fields.OptimizedImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Humana Apparels Ltd', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalNavbarSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('show_home', models.BooleanField(default=True)),
                ('show_about', models.BooleanField(default=True)),
                ('show_products', models.BooleanField(default=True)),
                ('show_customers', models.BooleanField(default=True)),
                ('show_compliance', models.BooleanField(default=True)),
                ('show_sustainability', models.BooleanField(default=True)),
                ('show_gallery', models.BooleanField(default=True)),
                ('show_news', models.BooleanField(default=True)),
                ('show_career', models.BooleanField(default=True)),
                ('show_contact', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Navbar Settings',
                'verbose_name_plural': 'historical Navbar Settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('show_home', models.BooleanField(default=True)),
                ('show_about', models.BooleanField(default=True)),
                ('show_products', models.BooleanField(default=True)),
                ('show_customers', models.BooleanField(default=True)),
                ('show_compliance', models.BooleanField(default=True)),
                ('show_sustainability', models.BooleanField(default=True)),
                ('show_gallery', models.BooleanField(default=True)),
                ('show_news', models.BooleanField(default=True)),
                ('show_career', models.BooleanField(default=True)),
                ('show_contact', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Navbar Settings',
                'verbose_name_plural': 'Navbar Settings',
            },
        ),
    ]
