# Generated by Django 6.0.6 on 2026-06-22 03:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapl', '0012_historicalmailsettings_mailsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sl_no', models.PositiveIntegerField(help_text='Display order number')),
                ('name', models.CharField(help_text='Certificate/Audit name', max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=200, null=True)),
                ('audit_date', models.CharField(blank=True, help_text='e.g. 31/10/2023 or 18 & 19 Jun 2025', max_length=100, null=True)),
                ('expiry_date', models.CharField(blank=True, help_text='e.g. 21/10/2027 or Running or Initial', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Running', 'Running'), ('Applied', 'Applied'), ('Initial Done', 'Initial Done')], default='Done', max_length=50)),
                ('result', models.CharField(blank=True, help_text='e.g. Certified, GOLD, Verified, B', max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='hapl.compliancepage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sl_no'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAuditStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sl_no', models.PositiveIntegerField(help_text='Display order number')),
                ('name', models.CharField(help_text='Certificate/Audit name', max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=200, null=True)),
                ('audit_date', models.CharField(blank=True, help_text='e.g. 31/10/2023 or 18 & 19 Jun 2025', max_length=100, null=True)),
                ('expiry_date', models.CharField(blank=True, help_text='e.g. 21/10/2027 or Running or Initial', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Running', 'Running'), ('Applied', 'Applied'), ('Initial Done', 'Initial Done')], default='Done', max_length=50)),
                ('result', models.CharField(blank=True, help_text='e.g. Certified, GOLD, Verified, B', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hapl.compliancepage')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical audit status',
                'verbose_name_plural': 'historical audit statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
