# Generated by Django 6.0.6 on 2026-06-24 09:57

from django.db import migrations


# The values previously hard-coded in templates/www/complience.html, moved into
# the database so the "Company Information" section is fully admin-managed while
# keeping the public page visually identical.
STATS = [
    {"icon": "ph-calendar-blank", "label": "Established", "value": "1986", "subtext": None},
    {"icon": "ph-ruler", "label": "Area", "value": "219,219 sq ft", "subtext": "13,577 sq m"},
    {"icon": "ph-users-three", "label": "Manpower", "value": "2,400", "subtext": None},
    {"icon": "ph-package", "label": "Capacity", "value": "150,000", "subtext": "Pcs / Month"},
    {"icon": "ph-clock-countdown", "label": "Shifts", "value": "3", "subtext": None},
    {"icon": "ph-rows", "label": "Total Lines", "value": "28", "subtext": None},
]

BUYERS = [
    {"name": "Hugo Boss", "percentage": "60%"},
    {"name": "Marco Polo", "percentage": "15%"},
    {"name": "Macy's", "percentage": "15%"},
    {"name": "Antailor", "percentage": "5%"},
    {"name": "Others", "percentage": "5%"},
]

STEPS = [
    {"name": "Cutting", "note": None},
    {"name": "Sewing", "note": "(Quilting, Downfilling)"},
    {"name": "Finishing", "note": None},
    {"name": "Packing", "note": None},
]


def seed_company_info(apps, schema_editor):
    CompliancePage = apps.get_model("hapl", "CompliancePage")
    ComplianceCompanyInfo = apps.get_model("hapl", "ComplianceCompanyInfo")
    CompanyInfoStat = apps.get_model("hapl", "CompanyInfoStat")
    CompanyBuyer = apps.get_model("hapl", "CompanyBuyer")
    ProductionStep = apps.get_model("hapl", "ProductionStep")

    page = CompliancePage.objects.first()
    if page is None:
        return

    ComplianceCompanyInfo.objects.get_or_create(
        page=page,
        defaults={"eyebrow": "At a Glance", "title": "Company Information"},
    )

    if not CompanyInfoStat.objects.filter(page=page).exists():
        for order, s in enumerate(STATS):
            CompanyInfoStat.objects.create(page=page, order=order, **s)

    if not CompanyBuyer.objects.filter(page=page).exists():
        for order, b in enumerate(BUYERS):
            CompanyBuyer.objects.create(page=page, order=order, **b)

    if not ProductionStep.objects.filter(page=page).exists():
        for order, st in enumerate(STEPS):
            ProductionStep.objects.create(page=page, order=order, **st)


def unseed_company_info(apps, schema_editor):
    CompliancePage = apps.get_model("hapl", "CompliancePage")
    page = CompliancePage.objects.first()
    if page is None:
        return
    apps.get_model("hapl", "CompanyInfoStat").objects.filter(page=page).delete()
    apps.get_model("hapl", "CompanyBuyer").objects.filter(page=page).delete()
    apps.get_model("hapl", "ProductionStep").objects.filter(page=page).delete()
    apps.get_model("hapl", "ComplianceCompanyInfo").objects.filter(page=page).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hapl', '0014_alter_compliancecertificate_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_company_info, unseed_company_info),
    ]
