# Generated by Django 6.0.8 on 2026-10-04 02:54

import common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hapl", "0015_seed_compliance_company_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Activities"},
        ),
        migrations.AlterModelOptions(
            name="auditstatus",
            options={"ordering": ["sl_no"], "verbose_name_plural": "Audit status"},
        ),
        migrations.AlterModelOptions(
            name="companystats",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Company stat",
                "verbose_name_plural": "Company stats",
            },
        ),
        migrations.AlterModelOptions(
            name="compliancesection",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="gallerysection",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="galleryvideo",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="historicalactivity",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical activity",
                "verbose_name_plural": "historical Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalauditstatus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical audit status",
                "verbose_name_plural": "historical Audit status",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcompanystats",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Company stat",
                "verbose_name_plural": "historical Company stats",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhomeherosection",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Home Hero",
                "verbose_name_plural": "historical Home Hero",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproductcategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical product category",
                "verbose_name_plural": "historical Product categories",
            },
        ),
        migrations.AlterModelOptions(
            name="homecarouselslide",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="homeherosection",
            options={"verbose_name": "Home Hero", "verbose_name_plural": "Home Hero"},
        ),
        migrations.AlterModelOptions(
            name="productcarouselslide",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["order", "id"],
                "verbose_name_plural": "Product categories",
            },
        ),
        migrations.AlterModelOptions(
            name="productsection",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="social",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="sustainabilitycertificate",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="sustainabilitysection",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="banner_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Optional background image for the page banner.",
                null=True,
                upload_to="pages/banners/",
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="activitiessection",
            name="banner_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Optional background image for the page banner.",
                null=True,
                upload_to="pages/banners/",
            ),
        ),
        migrations.AddField(
            model_name="activitiessection",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="activitiessection",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activitiessection",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activitiessection",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="activitiessection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="activitiessection",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="activitiessection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activitiessection",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="activitiessection",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="careersection",
            name="banner_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Optional background image for the page banner.",
                null=True,
                upload_to="pages/banners/",
            ),
        ),
        migrations.AddField(
            model_name="careersection",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="careersection",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="careersection",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="careersection",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="careersection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="careersection",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="careersection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="careersection",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="careersection",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="careersection",
            name="positions_empty_text",
            field=models.CharField(
                blank=True,
                help_text="Shown when there are no open positions.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="careersection",
            name="positions_title",
            field=models.CharField(
                blank=True, help_text='e.g. "Open Positions"', max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="companystats",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Readable description shown under the number.",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companystats",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, help_text="Animated number, e.g. 2400", null=True
            ),
        ),
        migrations.AddField(
            model_name="companystats",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="companystats",
            name="prefix",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="companystats",
            name="suffix",
            field=models.CharField(
                blank=True, help_text='e.g. "+", "K", "%"', max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="audit_description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="audit_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="audit_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="banner_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Optional background image for the page banner.",
                null=True,
                upload_to="pages/banners/",
            ),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="certificates_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="certificates_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="standards_description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="compliancepage",
            name="standards_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="compliancesection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text='Defaults to "Standard".',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliancesection",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="banner_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Optional background image for the page banner.",
                null=True,
                upload_to="pages/banners/",
            ),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="groups_empty_text",
            field=models.CharField(
                blank=True,
                help_text="Shown when no contact groups exist.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="groups_title",
            field=models.CharField(
                blank=True, help_text='e.g. "Key Contacts"', max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contactsection",
            name="socials_title",
            field=models.CharField(
                blank=True,
                help_text='e.g. "Connect With Us"',
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerssection",
            name="banner_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Optional background image for the page banner.",
                null=True,
                upload_to="pages/banners/",
            ),
        ),
        migrations.AddField(
            model_name="customerssection",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="customerssection",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerssection",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customerssection",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customerssection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="customerssection",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customerssection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerssection",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="customerssection",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="faqsection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="all_tab_label",
            field=models.CharField(
                blank=True,
                help_text='Filter tab label, e.g. "All"',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="banner_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Optional background image for the page banner.",
                null=True,
                upload_to="pages/banners/",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="videos_title",
            field=models.CharField(
                blank=True, help_text='e.g. "Videos"', max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="gallerysection",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="galleryvideo",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalaboutsection",
            name="banner_image",
            field=models.TextField(
                blank=True,
                help_text="Optional background image for the page banner.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalaboutsection",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalaboutsection",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalaboutsection",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalaboutsection",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalaboutsection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalaboutsection",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalaboutsection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalaboutsection",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalaboutsection",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalactivitiessection",
            name="banner_image",
            field=models.TextField(
                blank=True,
                help_text="Optional background image for the page banner.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalactivitiessection",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalactivitiessection",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalactivitiessection",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalactivitiessection",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalactivitiessection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalactivitiessection",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalactivitiessection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalactivitiessection",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalactivitiessection",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="banner_image",
            field=models.TextField(
                blank=True,
                help_text="Optional background image for the page banner.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="positions_empty_text",
            field=models.CharField(
                blank=True,
                help_text="Shown when there are no open positions.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcareersection",
            name="positions_title",
            field=models.CharField(
                blank=True, help_text='e.g. "Open Positions"', max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcompanystats",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Readable description shown under the number.",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcompanystats",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, help_text="Animated number, e.g. 2400", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcompanystats",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalcompanystats",
            name="prefix",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompanystats",
            name="suffix",
            field=models.CharField(
                blank=True, help_text='e.g. "+", "K", "%"', max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="audit_description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="audit_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="audit_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="banner_image",
            field=models.TextField(
                blank=True,
                help_text="Optional background image for the page banner.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="certificates_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="certificates_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="standards_description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancepage",
            name="standards_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompliancesection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text='Defaults to "Standard".',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcompliancesection",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="banner_image",
            field=models.TextField(
                blank=True,
                help_text="Optional background image for the page banner.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="groups_empty_text",
            field=models.CharField(
                blank=True,
                help_text="Shown when no contact groups exist.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="groups_title",
            field=models.CharField(
                blank=True, help_text='e.g. "Key Contacts"', max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontactsection",
            name="socials_title",
            field=models.CharField(
                blank=True,
                help_text='e.g. "Connect With Us"',
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomerssection",
            name="banner_image",
            field=models.TextField(
                blank=True,
                help_text="Optional background image for the page banner.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomerssection",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomerssection",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomerssection",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomerssection",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomerssection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomerssection",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomerssection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomerssection",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomerssection",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalfaqsection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="all_tab_label",
            field=models.CharField(
                blank=True,
                help_text='Filter tab label, e.g. "All"',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="banner_image",
            field=models.TextField(
                blank=True,
                help_text="Optional background image for the page banner.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="videos_title",
            field=models.CharField(
                blank=True, help_text='e.g. "Videos"', max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalgallerysection",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalgalleryvideo",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalhomecarouselslide",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Describe the image for screen readers.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhomecarouselslide",
            name="caption",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalhomecarouselslide",
            name="focal_point",
            field=models.CharField(
                choices=[("center", "Center"), ("top", "Top"), ("bottom", "Bottom")],
                default="center",
                help_text="Which part of the image stays visible when cropped.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="autoplay",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="autoplay_interval",
            field=models.PositiveSmallIntegerField(
                default=6,
                help_text="Seconds per slide.",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="bottom_label",
            field=models.CharField(
                blank=True,
                help_text='Label at the bottom of the text panel, e.g. "Humana Apparels Ltd"',
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="bottom_link_text",
            field=models.CharField(
                blank=True,
                help_text='e.g. "Inside our factory"',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="bottom_link_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="highlight_word",
            field=models.CharField(
                blank=True,
                help_text="Part of the title rendered in amber (must appear in the title).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Only the first active hero is shown."
            ),
        ),
        migrations.AddField(
            model_name="historicalhomeintroductionsection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhomeintroductionsection",
            name="cta_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalhomeintroductionsection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhomeservicessection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhomestatssection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproductcarouselslide",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalproductcategory",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalproductsection",
            name="eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalproductsection",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="banner_image",
            field=models.TextField(
                blank=True,
                help_text="Optional background image for the page banner.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="portfolio_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="portfolio_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalproductspage",
            name="portfolio_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="footer_address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="footer_contact_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="footer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="footer_links_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="footer_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="footer_social_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="header_cta_text",
            field=models.CharField(
                blank=True, help_text='e.g. "Get in touch"', max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="header_cta_url",
            field=models.CharField(
                blank=True, help_text="e.g. /contact/", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="logo_light",
            field=models.TextField(
                blank=True,
                help_text="White / light logo used on the navy header and footer.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitesettings",
            name="og_image",
            field=models.TextField(
                blank=True,
                help_text="Social sharing image (1200×630 recommended).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsocial",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitycertificate",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="banner_image",
            field=models.TextField(
                blank=True,
                help_text="Optional background image for the page banner.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="certificates_title",
            field=models.CharField(
                blank=True, help_text='e.g. "Recognized By"', max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitypage",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitysection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text='Defaults to "Chapter NN".',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsustainabilitysection",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalteamsection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaltestimonialssection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalwhyussection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homecarouselslide",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Describe the image for screen readers.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homecarouselslide",
            name="caption",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homecarouselslide",
            name="focal_point",
            field=models.CharField(
                choices=[("center", "Center"), ("top", "Top"), ("bottom", "Bottom")],
                default="center",
                help_text="Which part of the image stays visible when cropped.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="autoplay",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="autoplay_interval",
            field=models.PositiveSmallIntegerField(
                default=6,
                help_text="Seconds per slide.",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="bottom_label",
            field=models.CharField(
                blank=True,
                help_text='Label at the bottom of the text panel, e.g. "Humana Apparels Ltd"',
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="bottom_link_text",
            field=models.CharField(
                blank=True,
                help_text='e.g. "Inside our factory"',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="bottom_link_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="highlight_word",
            field=models.CharField(
                blank=True,
                help_text="Part of the title rendered in amber (must appear in the title).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Only the first active hero is shown."
            ),
        ),
        migrations.AddField(
            model_name="homeintroductionsection",
            name="cta_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homeintroductionsection",
            name="cta_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homeintroductionsection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homeservicessection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homestatssection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productcarouselslide",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productsection",
            name="eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productsection",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productspage",
            name="banner_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Optional background image for the page banner.",
                null=True,
                upload_to="pages/banners/",
            ),
        ),
        migrations.AddField(
            model_name="productspage",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="productspage",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productspage",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productspage",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productspage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="productspage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productspage",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productspage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="productspage",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productspage",
            name="portfolio_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productspage",
            name="portfolio_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="productspage",
            name="portfolio_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_contact_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_links_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_social_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_cta_text",
            field=models.CharField(
                blank=True, help_text='e.g. "Get in touch"', max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_cta_url",
            field=models.CharField(
                blank=True, help_text="e.g. /contact/", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_light",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="White / light logo used on the navy header and footer.",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="og_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Social sharing image (1200×630 recommended).",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AddField(
            model_name="social",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sustainabilitycertificate",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="banner_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Optional background image for the page banner.",
                null=True,
                upload_to="pages/banners/",
            ),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="banner_subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="Page banner heading. Falls back to the section title.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="certificates_title",
            field=models.CharField(
                blank=True, help_text='e.g. "Recognized By"', max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="cta_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="sustainabilitypage",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sustainabilitysection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text='Defaults to "Chapter NN".',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sustainabilitysection",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamsection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testimonialssection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whyussection",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the section title.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companystats",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="companystats",
            name="value",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalcompanystats",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalcompanystats",
            name="value",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalhomeherosection",
            name="badge_text",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the title",
                max_length=200,
                null=True,
                verbose_name="eyebrow",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhomeherosection",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Paragraph shown under the title.",
                max_length=500,
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsitesettings",
            name="footer_description",
            field=models.TextField(
                blank=True, help_text="Short about text in the footer.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalsitesettings",
            name="site_logo",
            field=models.TextField(
                blank=True,
                help_text="Logo for light backgrounds.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homeherosection",
            name="badge_text",
            field=models.CharField(
                blank=True,
                help_text="Small label shown above the title",
                max_length=200,
                null=True,
                verbose_name="eyebrow",
            ),
        ),
        migrations.AlterField(
            model_name="homeherosection",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Paragraph shown under the title.",
                max_length=500,
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_description",
            field=models.TextField(
                blank=True, help_text="Short about text in the footer.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_logo",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Logo for light backgrounds.",
                null=True,
                upload_to="settings/",
            ),
        ),
    ]
