# Generated by Django 6.0.8 on 2026-10-04 04:18

import common.fields
from django.db import migrations, models


# Copy previously hard-coded in templates/www/home.html and
# templates/www/partials/home_virtual_tour.html (master 5501e70).
HERO_CLOSING = {
    "closing_eyebrow": "Let’s work together",
    "closing_title": "Your next collection. Our next conversation.",
    "closing_button_text": "Talk to our team",
    "closing_button_url": "/contact/",
}
GALLERY_HOME = {
    "home_eyebrow": "Inside Humana",
    "home_title": "A closer look at our facilities.",
    "tour_url": "https://360vr.hameemgroup.com/humana/",
    "tour_eyebrow": "Virtual experience",
    "tour_title": "Explore Humana Apparels in 360°",
    "tour_text": (
        "Take an immersive virtual tour of our manufacturing facility and "
        "explore Humana Apparels from a new perspective."
    ),
    "tour_button_text": "Explore 360° Factory Tour",
}


def populate(apps, schema_editor):
    for model_name, values in (("HomeHeroSection", HERO_CLOSING), ("GalleryPage", GALLERY_HOME)):
        model = apps.get_model("hapl", model_name)
        for obj in model.objects.filter(deleted__isnull=True):
            changed = False
            for field, value in values.items():
                if getattr(obj, field) in (None, ""):
                    setattr(obj, field, value)
                    changed = True
            if changed:
                obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("hapl", "0017_populate_cms_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerypage",
            name="home_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="home_title",
            field=models.CharField(
                blank=True,
                help_text="Heading of the factory gallery strip on the home page.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="tour_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="tour_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="tour_image",
            field=common.fields.OptimizedImageField(
                blank=True,
                help_text="Preview image. Falls back to the first gallery image.",
                null=True,
                upload_to="gallery/tour/",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="tour_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="tour_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="tour_url",
            field=models.URLField(
                blank=True,
                help_text="External 360° tour; opens in a new tab. Leave empty to hide the tour block.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="home_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="home_title",
            field=models.CharField(
                blank=True,
                help_text="Heading of the factory gallery strip on the home page.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="tour_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="tour_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="tour_image",
            field=models.TextField(
                blank=True,
                help_text="Preview image. Falls back to the first gallery image.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="tour_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="tour_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalgallerypage",
            name="tour_url",
            field=models.URLField(
                blank=True,
                help_text="External 360° tour; opens in a new tab. Leave empty to hide the tour block.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="closing_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="closing_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="closing_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhomeherosection",
            name="closing_title",
            field=models.CharField(
                blank=True,
                help_text='Home page closing band, e.g. "Your next collection. Our next conversation."',
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="closing_button_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="closing_button_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="closing_eyebrow",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homeherosection",
            name="closing_title",
            field=models.CharField(
                blank=True,
                help_text='Home page closing band, e.g. "Your next collection. Our next conversation."',
                max_length=200,
                null=True,
            ),
        ),
        migrations.RunPython(populate, migrations.RunPython.noop),
    ]
